# Generated by Django 5.0.8 on 2024-08-21 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socios',
            old_name='cd',
            new_name='cp',
        ),
    ]
